spring.datasource.url: jdbc:mysql://localhost:3306/tracking
spring.datasource.username: root
spring.datasource.password: hWN-h2z-aPE-8dQ
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false